// <auto-generated />
namespace ForeScore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TeeTimeEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeeTimeEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202110231750294_TeeTimeEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
