// <auto-generated />
namespace ForeScore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NameProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100108314_NameProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
