// <auto-generated />
namespace ForeScore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NullTeeTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullTeeTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202111152000068_NullTeeTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
