// <auto-generated />
namespace ForeScore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Null));
        
        string IMigrationMetadata.Id
        {
            get { return "202111180026216_Null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
